"""notices table

Revision ID: 39bfc37094ad
Revises: 683974c8b543
Create Date: 2019-11-04 16:23:40.153898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bfc37094ad'
down_revision = '683974c8b543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_expiry'), 'notice', ['expiry'], unique=False)
    op.create_index(op.f('ix_notice_priority'), 'notice', ['priority'], unique=False)
    op.create_index(op.f('ix_notice_timestamp'), 'notice', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_timestamp'), table_name='notice')
    op.drop_index(op.f('ix_notice_priority'), table_name='notice')
    op.drop_index(op.f('ix_notice_expiry'), table_name='notice')
    op.drop_table('notice')
    # ### end Alembic commands ###
